export const variantsClasses = new Map()
variantsClasses.set('primary', 'bg-green-600 hover:bg-green-700 text-slate-50')

export const technologiesColorsClasses = new Map()
technologiesColorsClasses.set('HTML', 'bg-orange-500')
technologiesColorsClasses.set('CSS', 'bg-blue-500')
technologiesColorsClasses.set('JavaScript', 'bg-yellow-500')
technologiesColorsClasses.set('Vue', 'bg-green-600')
technologiesColorsClasses.set('TailwindCSS', 'bg-cyan-500')
technologiesColorsClasses.set('Laravel', 'bg-red-500')
technologiesColorsClasses.set('PHP', 'bg-purple-400')
technologiesColorsClasses.set('MySQL', 'bg-blue-600')
technologiesColorsClasses.set('MongoDB', 'bg-green-500')
technologiesColorsClasses.set('AWS', 'bg-orange-400')
technologiesColorsClasses.set('Bootstrap', 'bg-purple-500')
technologiesColorsClasses.set('CSS', 'bg-sky-500')
technologiesColorsClasses.set('SCSS', 'bg-rose-600')
technologiesColorsClasses.set('Node.js', 'bg-lime-600')
technologiesColorsClasses.set('Webpack', 'bg-cyan-500')
technologiesColorsClasses.set('Vite.js', 'bg-indigo-300')
technologiesColorsClasses.set('Typescript', 'bg-blue-400')
technologiesColorsClasses.set('Docker', 'bg-cyan-600')
technologiesColorsClasses.set('Jest', 'bg-red-800')
technologiesColorsClasses.set('Cypress', 'bg-slate-700')
technologiesColorsClasses.set('C', 'bg-slate-400')
technologiesColorsClasses.set('Java', 'bg-orange-700')
